name: deploy
on: workflow_dispatch
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run test
        run: pytest -v test_handlers.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
        
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        run: pip install -r requirements.tx

      - uses: akhileshns/heroku-deploy@v3.13.15 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-cv-bot"
          heroku_email: "sergybibik1234@gmail.com"
          procfile: "worker: python3 main.py"
        env: 
          HD_TOKEN: ${{secrets.TOKEN}}
   
